# frozen_string_literal: true

require_relative 'pieces/piece'
require_relative 'pieces/bishop'
require_relative 'pieces/king'
require_relative 'pieces/queen'
require_relative 'pieces/rook'
require_relative 'pieces/black_pawn'
require_relative 'pieces/white_pawn'
require_relative 'pieces/knight'
require_relative 'pieces/blank_piece'
require_relative 'board'
require_relative 'board_builder'
require_relative 'cell'
require_relative 'game'
